# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0c1de975d817411f75f016d10e27c709"
name = "cart-abd"
application_url = "https://c64fededf0be.ngrok-free.app"
embedded = true
handle = "cart-abd"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "carts/create" ]
  uri = "/webhooks/carts/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,unauthenticated_read_checkouts,unauthenticated_read_customers,unauthenticated_read_product_listings"

[auth]
redirect_urls = ["https://c64fededf0be.ngrok-free.app/auth/callback", "https://c64fededf0be.ngrok-free.app/auth/shopify/callback", "https://c64fededf0be.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
